name: GCP

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2.1.3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up environment variables
        run: |
          echo "DB_LOGIN=${{ secrets.DB_LOGIN }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DATABASE=${{ secrets.DATABASE }}" >> $GITHUB_ENV

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest .

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest

      - name: Deploy Docker image
        run: gcloud run deploy robotzproject --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest --region us-central1 --memory 512Mi --port 80 --min-instances 0 --max-instances 1 --platform managed --allow-unauthenticated