name: GCP

on:
    release:
        types: [published]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest
      DB_LOGIN: ${{ secrets.DB_LOGIN }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DATABASE: ${{ secrets.DATABASE }}
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2.1.3'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # # Login to GCP
      # - uses: google-github-actions/setup-gcloud@v2
      #   with:
      #     service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # build image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # deploy image
      - name: Deploy Docker image
        run: gcloud run deploy apiproexpres --image $IMAGE_NAME --region us-central1 --memory 512Mi --port 80 --min-instances 0 --max-instances 1 --platform managed --allow-unauthenticated